sudo: false
dist: trusty

addons:
  postgresql: "9.3"
  apt:
    packages:
      - postgresql-contrib-9.3

env:
  global:
    - SIMPLIFIED_TEST_DATABASE="postgres://simplified_test:test@localhost:5432/simplified_core_test"
    - SIMPLIFIED_ELASTICSEARCH_VERSION=6

services:
  - postgresql
  - elasticsearch

language: python

python:
  - "2.7"

cache: pip

before_install:
  - pip install --upgrade pip
  - pip install "setuptools>=18.5"
  - sleep 10

install:
  - pip install -r requirements.txt
  - python -m textblob.download_corpora

before_script:
  - psql -c 'create user simplified_test;' -U postgres
  - psql -c 'create database simplified_core_test;' -U postgres
  - psql -c 'grant all privileges on database simplified_core_test to simplified_test;' -U postgres
  - psql -c 'create extension pgcrypto;' -U postgres -d simplified_core_test

script:
  - wget -q --waitretry=1 --retry-connrefused -T 20 -O - http://127.0.0.1:9200
  - ./test
